# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 946d09ff0aba1eb5acd0c827cfa1b4cc2230762f179ae1fc5d1032f06ee5a401b77ea08132179f9d4829dee0e3612f8026a4129fe33cb25b06b7875f6c5996b8

test:
  secret_key_base: 8f11e1338f38a47c5f96bbc79ee29fbcafc0a5cd2731d38876fd0157bdb040a080e1033c5b3539dba45c9b3b6b8a972a937bdeb226d152fe1aa7056fe73149ce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 2300af5aaa4e349b1b8d1ff5b60c8dfa65e0dec8bc7f6734130074bddb22a4f13cbc1b7baddfcd553b95a5a31439b060c4d78d21fd5a94d8a3290c0d40ea8447
